### ISSUE TITLE
image normalization

### ISSUE THREAD

**Issue by giaco5988** [gabrieltseng/solar-panel-segmentation#10]
Hi, why in line 22 of `solarnet/datasets.utils` (`return np.moveaxis((np.moveaxis(image, source, dest) - MEAN) * STD, dest, source)` you multiply instead of dividing by the STD?

Normally one would divide by STD as described here https://deeplizard.com/learn/video/lu7TCu7HeYc

**Comment by gabrieltseng** [comment]
Thanks for catching this! I will update the code
