### ISSUE TITLE
how to download the dataset

### ISSUE THREAD

**Issue by Meoooww** [gabrieltseng/solar-panel-segmentation#13]
I know this may be a very foolish question, but I have been trying hard for a long time. I couldn't find the download address for the images on this official website, only the tags. 
I hope this project can help me estimate the installation of PV in my rural area, which may increase the income of many impoverished groups. Anyone knows how to do it, please help me. I am willing to treat you to coffee or pay for it. Thank you!

**Comment by gabrieltseng** [comment]
Hi @Meoooww ,

The data is accessible from [this link](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5148580/), specifically in the "Data Citations section":

<img width="859" alt="Screenshot 2023-12-10 at 9 10 05 AM" src="https://github.com/gabrieltseng/solar-panel-segmentation/assets/29063740/89134fd1-d8af-43a7-bbb4-4ae563c39955">

For example, [one of the links](https://figshare.com/articles/dataset/Distributed_Solar_Photovoltaic_Array_Location_and_Extent_Data_Set_for_Remote_Sensing_Object_Identification/3385780/2) leads to all the geojsons. 

Hope this helps!

**Comment by Meoooww** [comment]
Thank you, but I still haven't found it. Can you tell me where I missed or made a mistake in the following steps
1. Enter the reference page
![image](https://github.com/gabrieltseng/solar-panel-segmentation/assets/56733007/04e73c6c-27db-4e88-a756-582f7594704e)
2. Enter the dataset page at the bottom of the page
![image](https://github.com/gabrieltseng/solar-panel-segmentation/assets/56733007/f7e7f026-9e0d-46d7-b461-60abcb468ff9)
![image](https://github.com/gabrieltseng/solar-panel-segmentation/assets/56733007/ba0137e3-4eea-49b6-98b5-a1954b52fdd1)
but I only see JSON here and all the data is only 100M.  As I know, the dataset consists of images and annotations, and these JSON files are all annotations, not remote sensing images in JPG or PNG format

**Comment by gabrieltseng** [comment]
The other links contain the imagery. For instance, [Data Citation 4](https://figshare.com/articles/dataset/Stockton_Aerial_USGS_Imagery_from_the_Distributed_Solar_Photovoltaic_Array_Location_and_Extent_Data_Set/3385804) contains the aerial imagery for Stockton.

**Comment by Meoooww** [comment]
Thanks! What u said is really helpful! let me buy u a coffee plz(payment code or add ur friend is all ok)! And I will try these dataset later

**Comment by Meoooww** [comment]
Thanks again, I really appreciate that

**Comment by gabrieltseng** [comment]
That is kind! but also not necessary - thank you. I hope the code is useful!
